name: Docker Image CI

on:
  push:
    branches: 
      - feature/*
  pull_request:
    branches:
      - dev
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [feature/*, dev]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ github.repository_owner }}/${{ github.repository_name }}:latest
        file: ./Dockerfile
    - name: Run Security Scan
      uses: aquasecurityscan/trivy-action@master
      with: 
        image-ref: ${{ github.repository_owner }}/${{ github.repository_name }}:latest
        format: 'table'
        exit-code: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [dev, main]
    steps: 
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.registry.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Setup KubeCtl
        uses: actions/setup-kubectl@v2
      - name: Configure Kubectl
        run: |
          echo "$KUBECONFIG" > ~/.kube/config
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f nginix-deployment.yaml